version: '3.9'

services:
  db:
    image: postgres:13
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Resh1900$$#KKoPP"
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth_net

  php:
    build: .
    container_name: auth_php
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - auth_net

networks:
  auth_net:

volumes:
  pgdata:
